server:
  port: 9000
spring:
  application:
    name: demo-config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangzhihaolighter/config-repo-demo
#          git仓库私有，需要登录，配置用户名与密码
#          username:
#          password:

#eureka server
eureka:
  server:
    hostname: localhost
    port: 8000
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/